from fastapi import APIRouter
from .endpoints import admin, agents, assets, audit_logs, auth, compliance, connectors, coverage, detections, events, hunting, incidents, notifications, overview, reports, rules, saved_queries, threat_intel, users, websocket, webhook_ingest

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(overview.router)
api_router.include_router(coverage.router)
api_router.include_router(detections.router)
api_router.include_router(incidents.router)
api_router.include_router(rules.router)
api_router.include_router(connectors.router)
api_router.include_router(users.router)
api_router.include_router(events.router)
api_router.include_router(hunting.router)
api_router.include_router(saved_queries.router)
api_router.include_router(websocket.router)
api_router.include_router(admin.router)
api_router.include_router(threat_intel.router)
api_router.include_router(assets.router)
api_router.include_router(audit_logs.router)
api_router.include_router(agents.router)
api_router.include_router(reports.router)
api_router.include_router(compliance.router)
api_router.include_router(webhook_ingest.router)
api_router.include_router(notifications.router)
