"""
NDR Detection Engine — network-based threat detection algorithms.

Ported from KYRA MDR's NdrDetectionEngine.java.
Runs as part of the event processing pipeline, analyzing network flow data
for indicators of compromise.

Algorithms:
  1. Port Scan Detection (T1046 — Network Service Discovery)
  2. C2 Beaconing Detection (T1071 — Application Layer Protocol)
  3. Lateral Movement Detection (T1021 — Remote Services)
  4. Data Exfiltration Detection (T1041 — Exfiltration Over C2 Channel)
  5. DNS Anomaly Detection (T1071.004 — DNS, T1568 — Dynamic Resolution)
  6. Brute Force Detection (T1110 — Brute Force)

Each detector maintains in-memory state for sliding window analysis.
Alerts are created via the alert manager with MITRE ATT&CK context.
"""

from __future__ import annotations

import math
import time
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from ..core.logging import get_logger

logger = get_logger(__name__)

# ============================================================
# Constants & Thresholds
# ============================================================

PORT_SCAN_THRESHOLD = 15  # distinct ports in window
PORT_SCAN_WINDOW_SEC = 300  # 5 minutes

C2_MIN_CONNECTIONS = 10
C2_MAX_JITTER = 0.20  # 20%
C2_MIN_INTERVAL_MS = 1000  # ignore sub-second noise

LATERAL_MOVEMENT_PORTS = frozenset({445, 3389, 22, 135, 5985, 5986})

EXFIL_BASELINE_MULTIPLIER = 2.0

DNS_PORT = 53
DNS_TUNNEL_MIN_BYTES = 100
DGA_ENTROPY_THRESHOLD = 3.5

BRUTE_FORCE_THRESHOLD = 10  # attempts in window
BRUTE_FORCE_WINDOW_SEC = 300  # 5 minutes
BRUTE_FORCE_MAX_DURATION_MS = 2000
BRUTE_FORCE_MAX_BYTES = 1000
AUTH_PORTS = frozenset({22, 23, 3389, 5900, 445, 21, 110, 143, 993, 995, 389, 636})

# RFC 1918 private ranges
_PRIVATE_PREFIXES = ("10.", "172.16.", "172.17.", "172.18.", "172.19.",
                     "172.20.", "172.21.", "172.22.", "172.23.", "172.24.",
                     "172.25.", "172.26.", "172.27.", "172.28.", "172.29.",
                     "172.30.", "172.31.", "192.168.")

STATE_PRUNE_INTERVAL_SEC = 60


# ============================================================
# Data types
# ============================================================

@dataclass
class NdrAlert:
    """Alert generated by NDR detection."""
    alert_type: str
    severity: str
    src_ip: str
    dst_ip: str | None = None
    dst_port: int | None = None
    description: str = ""
    mitre_technique: str = ""
    mitre_tactic: str = ""
    confidence: float = 0.80
    evidence: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class FlowRecord:
    """Simplified network flow record."""
    src_ip: str
    dst_ip: str
    src_port: int
    dst_port: int
    protocol: str  # TCP, UDP, ICMP
    bytes_in: int = 0
    bytes_out: int = 0
    duration_ms: int = 0
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


# ============================================================
# NDR Detection Engine
# ============================================================

class NdrDetectionEngine:
    """Stateful network detection engine with 6 detection algorithms."""

    def __init__(self) -> None:
        # Port scan state: {src_ip: [(port, dst_ip, timestamp), ...]}
        self._port_scan_state: dict[str, list[tuple[int, str, float]]] = defaultdict(list)

        # C2 beaconing state: {src_ip::dst_ip:port: [timestamps]}
        self._beacon_state: dict[str, list[float]] = defaultdict(list)

        # Brute force state: {src_ip:dst_port: [timestamps]}
        self._brute_force_state: dict[str, list[float]] = defaultdict(list)

        # Outbound volume state: {src_ip: total_bytes}
        self._outbound_volume: dict[str, int] = defaultdict(int)

        # Baseline: {metric_name: mean_value}
        self._baselines: dict[str, float] = {}

        # Known internal communication pairs
        self._known_pairs: set[tuple[str, str]] = set()

        # Dedup: {alert_key: last_alert_time}
        self._alert_dedup: dict[str, float] = {}
        self._dedup_window_sec = 1800  # 30 minutes

        self._last_prune = time.monotonic()

    def analyze_flow(self, flow: FlowRecord) -> list[NdrAlert]:
        """Analyze a single flow record through all detectors. Returns alerts."""
        alerts: list[NdrAlert] = []
        now = time.monotonic()

        # Periodic state pruning
        if now - self._last_prune > STATE_PRUNE_INTERVAL_SEC:
            self._prune_state()
            self._last_prune = now

        ts = flow.timestamp.timestamp()

        # 1. Port scan detection
        alert = self._detect_port_scan(flow, ts)
        if alert:
            alerts.append(alert)

        # 2. C2 beaconing detection (outbound only)
        if not self._is_private(flow.dst_ip):
            alert = self._detect_c2_beaconing(flow, ts)
            if alert:
                alerts.append(alert)

        # 3. Lateral movement (internal-to-internal on sensitive ports)
        if self._is_private(flow.src_ip) and self._is_private(flow.dst_ip):
            alert = self._detect_lateral_movement(flow)
            if alert:
                alerts.append(alert)

        # 4. Data exfiltration (outbound volume anomaly)
        if self._is_private(flow.src_ip) and not self._is_private(flow.dst_ip):
            alert = self._detect_exfiltration(flow)
            if alert:
                alerts.append(alert)

        # 5. DNS anomaly
        if flow.dst_port == DNS_PORT:
            alert = self._detect_dns_anomaly(flow)
            if alert:
                alerts.append(alert)

        # 6. Brute force
        if flow.dst_port in AUTH_PORTS:
            alert = self._detect_brute_force(flow, ts)
            if alert:
                alerts.append(alert)

        return alerts

    def analyze_batch(self, flows: list[FlowRecord]) -> list[NdrAlert]:
        """Analyze a batch of flow records."""
        all_alerts: list[NdrAlert] = []
        for flow in flows:
            all_alerts.extend(self.analyze_flow(flow))
        return all_alerts

    # ============================================================
    # Detection Algorithms
    # ============================================================

    def _detect_port_scan(self, flow: FlowRecord, ts: float) -> NdrAlert | None:
        """Detect port scanning: 15+ distinct ports from same source in 5 min."""
        key = flow.src_ip
        self._port_scan_state[key].append((flow.dst_port, flow.dst_ip, ts))

        # Count distinct ports in window
        cutoff = ts - PORT_SCAN_WINDOW_SEC
        recent = [(p, d, t) for p, d, t in self._port_scan_state[key] if t > cutoff]
        self._port_scan_state[key] = recent  # prune old entries

        # Group by destination IP
        by_dst: dict[str, set[int]] = defaultdict(set)
        for port, dst, _ in recent:
            by_dst[dst].add(port)

        for dst_ip, ports in by_dst.items():
            if len(ports) >= PORT_SCAN_THRESHOLD:
                alert_key = f"port_scan:{flow.src_ip}:{dst_ip}"
                if self._is_deduped(alert_key):
                    continue
                return NdrAlert(
                    alert_type="PORT_SCAN",
                    severity="medium",
                    src_ip=flow.src_ip,
                    dst_ip=dst_ip,
                    description=f"Port scan: {flow.src_ip} scanned {len(ports)} ports on {dst_ip} in 5 min",
                    mitre_technique="T1046",
                    mitre_tactic="Discovery",
                    confidence=0.85,
                    evidence={"distinct_ports": len(ports), "ports_sample": sorted(ports)[:20]},
                )
        return None

    def _detect_c2_beaconing(self, flow: FlowRecord, ts: float) -> NdrAlert | None:
        """Detect C2 beaconing: regular interval connections with <20% jitter."""
        key = f"{flow.src_ip}::{flow.dst_ip}:{flow.dst_port}"
        self._beacon_state[key].append(ts)

        timestamps = self._beacon_state[key]
        if len(timestamps) < C2_MIN_CONNECTIONS:
            return None

        # Sort and calculate inter-arrival times
        timestamps.sort()
        intervals = [timestamps[i] - timestamps[i - 1] for i in range(1, len(timestamps))]
        # Filter out sub-second noise
        intervals = [iv for iv in intervals if iv > C2_MIN_INTERVAL_MS / 1000.0]

        if len(intervals) < C2_MIN_CONNECTIONS - 1:
            return None

        mean_interval = sum(intervals) / len(intervals)
        if mean_interval <= 0:
            return None

        variance = sum((iv - mean_interval) ** 2 for iv in intervals) / len(intervals)
        stddev = math.sqrt(variance)
        jitter = stddev / mean_interval

        if jitter < C2_MAX_JITTER:
            alert_key = f"c2_beacon:{flow.src_ip}:{flow.dst_ip}:{flow.dst_port}"
            if self._is_deduped(alert_key):
                return None
            return NdrAlert(
                alert_type="C2_BEACONING",
                severity="high",
                src_ip=flow.src_ip,
                dst_ip=flow.dst_ip,
                dst_port=flow.dst_port,
                description=(
                    f"C2 beaconing: {flow.src_ip} → {flow.dst_ip}:{flow.dst_port} "
                    f"every {mean_interval:.1f}s (jitter={jitter*100:.1f}%)"
                ),
                mitre_technique="T1071",
                mitre_tactic="Command and Control",
                confidence=min(0.95, 1.0 - jitter),
                evidence={
                    "connections": len(timestamps),
                    "mean_interval_sec": round(mean_interval, 2),
                    "jitter_pct": round(jitter * 100, 1),
                },
            )
        return None

    def _detect_lateral_movement(self, flow: FlowRecord) -> NdrAlert | None:
        """Detect lateral movement: unusual internal connections on sensitive ports."""
        if flow.dst_port not in LATERAL_MOVEMENT_PORTS:
            return None

        pair = (flow.src_ip, flow.dst_ip)
        if pair in self._known_pairs:
            return None

        # First time seeing this internal pair on sensitive port
        self._known_pairs.add(pair)

        protocol_map = {445: "SMB", 3389: "RDP", 22: "SSH", 135: "RPC", 5985: "WinRM", 5986: "WinRM"}
        protocol = protocol_map.get(flow.dst_port, f"port {flow.dst_port}")

        alert_key = f"lateral:{flow.src_ip}:{flow.dst_ip}:{flow.dst_port}"
        if self._is_deduped(alert_key):
            return None

        return NdrAlert(
            alert_type="LATERAL_MOVEMENT",
            severity="high",
            src_ip=flow.src_ip,
            dst_ip=flow.dst_ip,
            dst_port=flow.dst_port,
            description=f"Lateral movement: {flow.src_ip} → {flow.dst_ip} via {protocol} (first observed)",
            mitre_technique="T1021",
            mitre_tactic="Lateral Movement",
            confidence=0.75,
            evidence={"protocol": protocol, "port": flow.dst_port},
        )

    def _detect_exfiltration(self, flow: FlowRecord) -> NdrAlert | None:
        """Detect data exfiltration: outbound volume >2x baseline."""
        total_bytes = flow.bytes_out + flow.bytes_in
        self._outbound_volume[flow.src_ip] += total_bytes

        baseline = self._baselines.get("outbound_bytes", 0)
        if baseline <= 0:
            return None

        current = self._outbound_volume[flow.src_ip]
        if current > baseline * EXFIL_BASELINE_MULTIPLIER:
            alert_key = f"exfil:{flow.src_ip}"
            if self._is_deduped(alert_key):
                return None

            ratio = current / baseline
            return NdrAlert(
                alert_type="DATA_EXFILTRATION",
                severity="critical",
                src_ip=flow.src_ip,
                dst_ip=flow.dst_ip,
                description=(
                    f"Data exfiltration: {flow.src_ip} sent {self._human_bytes(current)} "
                    f"(baseline: {self._human_bytes(int(baseline))}, {ratio:.1f}x)"
                ),
                mitre_technique="T1041",
                mitre_tactic="Exfiltration",
                confidence=0.80,
                evidence={
                    "total_bytes": current,
                    "baseline_bytes": int(baseline),
                    "ratio": round(ratio, 2),
                },
            )
        return None

    def _detect_dns_anomaly(self, flow: FlowRecord) -> NdrAlert | None:
        """Detect DNS anomaly: tunneling (large DNS) or DGA (high entropy)."""
        total_bytes = flow.bytes_out + flow.bytes_in
        if total_bytes > DNS_TUNNEL_MIN_BYTES:
            alert_key = f"dns_tunnel:{flow.src_ip}:{flow.dst_ip}"
            if self._is_deduped(alert_key):
                return None
            return NdrAlert(
                alert_type="DNS_ANOMALY",
                severity="high",
                src_ip=flow.src_ip,
                dst_ip=flow.dst_ip,
                dst_port=DNS_PORT,
                description=f"DNS tunneling: {flow.src_ip} → {flow.dst_ip}, {total_bytes} bytes in DNS request",
                mitre_technique="T1071.004",
                mitre_tactic="Command and Control",
                confidence=0.70,
                evidence={"dns_bytes": total_bytes, "threshold": DNS_TUNNEL_MIN_BYTES},
            )
        return None

    def _detect_brute_force(self, flow: FlowRecord, ts: float) -> NdrAlert | None:
        """Detect brute force: 10+ short-duration connections on auth ports in 5 min."""
        # Short duration + low bytes = failed auth attempt
        if flow.duration_ms > BRUTE_FORCE_MAX_DURATION_MS or flow.bytes_in > BRUTE_FORCE_MAX_BYTES:
            return None

        key = f"{flow.src_ip}:{flow.dst_port}"
        self._brute_force_state[key].append(ts)

        cutoff = ts - BRUTE_FORCE_WINDOW_SEC
        recent = [t for t in self._brute_force_state[key] if t > cutoff]
        self._brute_force_state[key] = recent

        if len(recent) >= BRUTE_FORCE_THRESHOLD:
            alert_key = f"brute_force:{flow.src_ip}:{flow.dst_port}"
            if self._is_deduped(alert_key):
                return None
            return NdrAlert(
                alert_type="BRUTE_FORCE",
                severity="high",
                src_ip=flow.src_ip,
                dst_ip=flow.dst_ip,
                dst_port=flow.dst_port,
                description=f"Brute force: {flow.src_ip} made {len(recent)} failed attempts on port {flow.dst_port} in 5 min",
                mitre_technique="T1110",
                mitre_tactic="Credential Access",
                confidence=0.85,
                evidence={"attempts": len(recent), "port": flow.dst_port, "window_sec": BRUTE_FORCE_WINDOW_SEC},
            )
        return None

    # ============================================================
    # Helpers
    # ============================================================

    @staticmethod
    def _is_private(ip: str) -> bool:
        return any(ip.startswith(p) for p in _PRIVATE_PREFIXES)

    def _is_deduped(self, key: str) -> bool:
        """Check if alert was already raised within dedup window."""
        now = time.monotonic()
        if key in self._alert_dedup and now - self._alert_dedup[key] < self._dedup_window_sec:
            return True
        self._alert_dedup[key] = now
        return False

    @staticmethod
    def _human_bytes(b: int) -> str:
        for unit in ("B", "KB", "MB", "GB"):
            if abs(b) < 1024:
                return f"{b:.1f} {unit}"
            b //= 1024
        return f"{b:.1f} TB"

    @staticmethod
    def calculate_domain_entropy(domain: str) -> float:
        """Calculate Shannon entropy for DGA detection. >3.5 = suspicious."""
        label = domain.split(".")[0] if "." in domain else domain
        if not label:
            return 0.0
        freq: dict[str, int] = defaultdict(int)
        for c in label:
            freq[c] += 1
        total = len(label)
        return -sum((count / total) * math.log2(count / total) for count in freq.values())

    def set_baseline(self, metric: str, value: float) -> None:
        """Set a baseline value for anomaly detection."""
        self._baselines[metric] = value

    def add_known_pair(self, src_ip: str, dst_ip: str) -> None:
        """Register a known internal communication pair (suppress lateral movement alerts)."""
        self._known_pairs.add((src_ip, dst_ip))

    def _prune_state(self) -> None:
        """Remove expired entries from all state maps."""
        now = time.monotonic()

        # Prune port scan state (keep last 5 min)
        cutoff = now - PORT_SCAN_WINDOW_SEC
        for key in list(self._port_scan_state.keys()):
            self._port_scan_state[key] = [(p, d, t) for p, d, t in self._port_scan_state[key] if t > cutoff]
            if not self._port_scan_state[key]:
                del self._port_scan_state[key]

        # Prune brute force state
        for key in list(self._brute_force_state.keys()):
            self._brute_force_state[key] = [t for t in self._brute_force_state[key] if t > cutoff]
            if not self._brute_force_state[key]:
                del self._brute_force_state[key]

        # Prune beacon state (keep last 1 hour)
        beacon_cutoff = now - 3600
        for key in list(self._beacon_state.keys()):
            self._beacon_state[key] = [t for t in self._beacon_state[key] if t > beacon_cutoff]
            if not self._beacon_state[key]:
                del self._beacon_state[key]

        # Prune dedup state
        dedup_cutoff = now - self._dedup_window_sec
        self._alert_dedup = {k: v for k, v in self._alert_dedup.items() if v > dedup_cutoff}

        # Reset hourly outbound volumes
        self._outbound_volume.clear()
